postgres:
  image: postgres:9.5
  environment:
    - POSTGRES_PASSWORD=mypassword

web:
  build: .
  ports:
    - "80:3000"
  links:
    - postgres
  environment:
    - PORT=3000
    - DATABASE_URL=postgres://postgres:mypassword@postgres:5432/postgres
    - MAILTRAP_API_TOKEN=b9a64f1a0892ebd
    - APP_URL=http://localhost/
